#server:
#  port: 9999
## spring:
##   cloud:
##     sentinel:
##       transport:
##         port: 8850
##         dashboard: 116.196.77.250:8849
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#feign:
#  httpclient:
#    enabled: false
#  okhttp:
#    enabled: true
mysql:
  url: haha
spring:
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: localhost:9876
      bindings:
        output:
          destination: topicTest
          group: test-group1
